### ISSUE TITLE
Rename R to RR

### ISSUE THREAD

**Issue by krlmlr** [wch/r-debug#1]
Starting R with `R` is now in my muscle memory, I'd rather see an error when starting `R` in this container instead. Do you see a problem with renaming the executable to `RR` or anything else?

**Comment by wch** [comment]
I sympathize with the muscle memory issue, but in this Dockerfile, `R` is installed with `apt-get`.

**Comment by krlmlr** [comment]
We still can rename the file. `apt` won't be happy, but do we care?

**Comment by eddelbuettel** [comment]
Recall that `$PATH` starts in `/usr/local` so why not do something like

```sh
cd /usr/local/bin && ln -s /usr/bin/R/ RR
```

which should satisfy both sides giving you `R` (as before) and `RR`.

**Comment by krlmlr** [comment]
Yes, but I was looking for a situation where running `R` just fails and makes me think which flavor of R I really want to use.

**Comment by krlmlr** [comment]
I can work around.
