### ISSUE TITLE
Daily builds appear to be broken

### ISSUE THREAD

**Issue by jameslamb** [wch/r-debug#35]
The README says the following (my emphasis):

> _... the following Docker images are built **daily** and pushed to Docker Hub_

At https://hub.docker.com/r/wch1/r-debug/tags, it looks like a new image has not been pushed since 2 months ago.

<img width="1282" alt="Screen Shot 2024-03-18 at 2 11 49 PM" src="https://github.com/wch/r-debug/assets/7608904/daf5b616-20cf-4cb4-92bd-e72f6201d403">

Could you please look into that, and get the builds going again so they keep up with changes to R-devel?

If you could point me at logs or configuration for these builds, I'd be happy to try to help.

**Comment by wch** [comment]
Somehow my build machine got a corrupted Docker installation. I'll see if I can fix it.

**Comment by wch** [comment]
I think it's fixed now, so I'll close this issue. (The build will take a while to finish.)

**Comment by jameslamb** [comment]
Thanks so much for the quick response! I see the new images now and they're working great.
