### ISSUE TITLE
Should use THREADCHECK instead of ASSERT_R_THREAD()

### ISSUE THREAD

**Issue by wch** [wch/r-debug#7]
As of 
https://github.com/wch/r-source/commit/3c59cea18594f41106596c4d3a8908144a1e70e8, R itself has a `THREADCHECK` macro to make sure that various functions are called from the correct thread.

Commit https://github.com/wch/r-source/commit/5cf1f4b365a7d32cdf6a1009131509448d9dc989 also added the checks that were in `ASSERT_R_THREAD()`.

The  assertthread build should be changed to use the built-in checks.

**Comment by jeroen** [comment]
Cool! Do these macro's prevent the GC from running in a non-main thread?

**Comment by wch** [comment]
Yes, I believe that if it tries to do GC in a thread, it calls `R_suicide()`, which I assume kills the R process. :)

The first link above was previously incorrect, but I've fixed it, and if you follow it you can see how it works. Just curious: in your work, have you had problems with GC in other threads?

**Comment by jeroen** [comment]
I avoid calling the R api in threads because afaik none of the api's are thread-safe due to the random GC runs. I was hoping these changes could help with suspending the GC in threads, but I guess that is not the purpose here :)

**Comment by wch** [comment]
Fixed in e9899c3.

**Comment by wch** [comment]
@jeroen I think the problem is even worse than having GC events run in the wrong thread. If you do any R memory management at all in a different thread, there's the possibility of memory corruption due to races. For example, if you look at https://github.com/wch/r-source/commit/5cf1f4b365a7d32cdf6a1009131509448d9dc989, you can see that `protect()` and `unprotect()` manipulate `R_PPStack`, and similarly, `R_PreserveObject()` and `R_ReleaseObject()` manipulate `R_PreciousList`. In the past I have run into many weird, hard-to-reproduce bugs because of these races.

But I agree about the overall lesson: don't call the R API from a different thread.
